name: page publish

on:
  push:
    branches:
      - "main"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Modify package.json
        run: |
          cd capacitor/purejs
          ls -l
          find . -name "package.json" -exec sed -i 's/"file:.*"/"latest"/g' {} \;
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_ACCESS_TOKEN}}" > .npmrc
          rm package-lock.json
          npm i
          npm run build
      
      # - name: Deploy 🚀
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: capacitor/purejs/dist