name: page publish

on:
  push:
    branches:
      - "main"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create cache key file
        run: |
          find . -name "package.json" | xargs -I {} md5sum {} > list.txt
      
      - name: cache
        uses: actions/cache@v3
        with:
          path: dist
          key: -${{ hashFiles('**/package.json') }}
      
      - name: Setup Node
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Modify package.json
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p dist/capacitor/purejs/
          chmod +x ./capacitor/purejs/build.sh

          find ./capacitor/purejs -name "package.json" \
            -exec ./capacitor/purejs/build.sh {} dist/capacitor/purejs/ ${{secrets.NPM_READ_ONLY_TOKEN}} \;
      
      - name: Modify package.json
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          chmod +x ./capacitor/build-index.sh
          cd dist/
          ../capacitor/build-index.sh .

      - name: Deploy 🚀
        if: steps.cache.outputs.cache-hit != 'true'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/