name: page publish

on:
  workflow_dispatch:
    inputs:
      core_plugin_versison: 
        description: 'The version of the @mkgeeklab/googlemaps-core-common plugin'
        required: false
        default: 'latest'
        type: string

      browser_plugin_version:
        description: 'The version of the @mkgeeklab/googlemaps-platform-browser plugin'
        required: false
        default: 'latest'
        type: string

      bridge_plugin_version:
        description: 'The version of the @mkgeeklab/googlemaps-bridge-capacitor plugin'
        required: false
        default: 'latest'
        type: string
        
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: cache
        uses: actions/cache@v3
        with:
          path: dist
          key: ${{ hashFiles('capacitor/**/*.js', 'capacitor/**/*.css', 'capacitor/**/*.html') }}
      
      - name: Setup Node
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Replace Google Maps API keys
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          find . -name "*.js" -exec \
            sed -i 's/\$GOOGLE_MAPS_JS_KEY/${{secrets.GOOGLE_MAPS_API_KEY}}/g' {} \;

      - name: Modify package.json
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p dist/capacitor/purejs/
          chmod +x ./capacitor/purejs/build.sh

          find ./capacitor/purejs -name "package.json" \
            -exec ./capacitor/purejs/build.sh \
              INPUT_FILE_PATH={} \
              NPM_TOKEN=${{secrets.NPM_READ_ONLY_TOKEN}} \
              CORE_PLUGIN_VERSION=${{ github.event.inputs.core_plugin_versison }} \
              BROWSER_PLUGIN_VERSION=${{ github.event.inputs.browser_plugin_version }} \
              BRIDGE_PLUGIN_VERSION=${{ github.event.inputs.bridge_plugin_version }} \;
      
      - name: Modify package.json
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          chmod +x ./build-index.sh
          ./build-index.sh capacitor/purejs dist/capacitor/purejs/index.html 
          tree dist/
          cat dist/capacitor/purejs/index.html 

      - name: Deploy 🚀
        if: steps.cache.outputs.cache-hit != 'true'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/capacitor/purejs/